<?php
if (!defined('ABSPATH')) exit;
$cvi_td = 'crescent-visibility';
?>
<div class="wrap">
    <h1>
        <?php esc_html_e('Crescent Visibility Data Management', 'crescent-visibility'); ?>
        <span style="font-size:13px;color:#646970;font-weight:400;"><?php
            /* translators: %s: plugin version */
            echo esc_html(sprintf(__('(plugin v%s)', 'crescent-visibility'), defined('CVI_VERSION') ? CVI_VERSION : '?'));
        ?></span>
    </h1>

    <div style="max-width: 800px;">
        <p><strong><?php esc_html_e('This plugin does not contain any visibility data by default.', 'crescent-visibility'); ?></strong></p>

        <p><?php esc_html_e('To use it, you must import a data file generated by the offline generator tool.', 'crescent-visibility'); ?></p>

        <h2><?php esc_html_e('How to Use', 'crescent-visibility'); ?></h2>
        <ol>
            <li><?php esc_html_e('Generate a .json data file with the project\'s generator. Years and cities are set there:', 'crescent-visibility'); ?><br>
                <code>go run generator/generate_visibility_data.go --start 2026 --end 2035 --cities jerusalem,dallas,melbourne --output ../data/visibility.json</code><br>
                <span style="color:#555;"><?php esc_html_e('The dropdown shows every city in the file (Jerusalem, Dallas and Melbourne are always included); the Year list shows every year in the file.', 'crescent-visibility'); ?></span>
            </li>
            <li><?php esc_html_e('Upload that file below to import the data into your WordPress database.', 'crescent-visibility'); ?></li>
            <li><?php esc_html_e('Use the shortcode on any page or post, for example:', 'crescent-visibility'); ?><br>
                <code>[crescent_visibility city="jerusalem" years="2026-2035"]</code>
            </li>
            <li><strong><?php esc_html_e('New (recommended for most users):', 'crescent-visibility'); ?></strong> <?php esc_html_e('For the full interactive experience:', 'crescent-visibility'); ?><br>
                <code>[crescent_visibility_interactive]</code> <?php esc_html_e('or', 'crescent-visibility'); ?> <code>[crescent_visibility_point]</code><br>
                <span style="color:#555;"><?php esc_html_e('Optional attributes: default_city="cairo" and theme="dark".', 'crescent-visibility'); ?></span>
            </li>
        </ol>

        <p><em><?php esc_html_e('You can re-import updated data files at any time to refresh or extend the dataset (for example, adding 2029 data later).', 'crescent-visibility'); ?></em></p>

        <div style="background:#fff3cd; border:1px solid #ffeaa7; padding:12px; border-radius:6px; margin:15px 0;">
            <strong><?php esc_html_e('Important for the interactive experience:', 'crescent-visibility'); ?></strong><br>
            <?php esc_html_e('The database is upgraded automatically when you update the plugin (per-evening Age/Q columns are added if missing). Those columns are only populated from your data file, so re-import after updating to get the richest result cards.', 'crescent-visibility'); ?>
        </div>

        <hr>

        <h2><?php esc_html_e('Import Data', 'crescent-visibility'); ?></h2>
        <p><?php esc_html_e('Upload a JSON file containing pre-computed visibility data.', 'crescent-visibility'); ?></p>

        <form method="post" enctype="multipart/form-data">
            <?php wp_nonce_field('crescent_import_nonce'); ?>
            <input type="file" name="import_file" accept=".json" required style="margin-bottom: 10px;">
            <br>
            <button type="submit" name="crescent_import" class="button button-primary"><?php esc_html_e('Import / Update Data', 'crescent-visibility'); ?></button>
        </form>

        <hr>

        <h2><?php esc_html_e('Reset Database Tables', 'crescent-visibility'); ?></h2>
        <p><?php esc_html_e('Permanently delete the plugin\'s tables (observations + cities) and recreate them empty. Use this if the data looks stuck or corrupted (e.g. only 1 row stored), then re-import. This does not affect any other plugin or content.', 'crescent-visibility'); ?></p>
        <?php
        global $wpdb;
        $cvi_drop_count = (int) $wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}crescent_observations");
        ?>
        <button type="button" class="button button-secondary cvi-danger-btn" id="cvi-drop-open"><?php esc_html_e('Drop & Recreate Tables…', 'crescent-visibility'); ?></button>

        <!-- Confirmation modal -->
        <div id="cvi-drop-modal" class="cvi-modal" hidden>
            <div class="cvi-modal__backdrop" data-cvi-close="1"></div>
            <div class="cvi-modal__box" role="dialog" aria-modal="true" aria-labelledby="cvi-drop-title">
                <h2 id="cvi-drop-title" class="cvi-modal__title"><?php esc_html_e('⚠️ Delete all crescent visibility data?', 'crescent-visibility'); ?></h2>
                <p><?php
                    /* translators: 1: observations table name, 2: cities table name */
                    echo esc_html(sprintf(
                        __('This permanently deletes the %1$s and %2$s tables and recreates them empty. There is no undo. You will need to re-import your JSON afterward.', 'crescent-visibility'),
                        $wpdb->prefix . 'crescent_observations',
                        $wpdb->prefix . 'crescent_cities'
                    ));
                ?></p>
                <p style="margin:10px 0;"><?php
                    /* translators: %s: number of stored observation rows */
                    echo esc_html(sprintf(
                        _n('Currently stored: %s observation row.', 'Currently stored: %s observation rows.', $cvi_drop_count, 'crescent-visibility'),
                        number_format($cvi_drop_count)
                    ));
                ?></p>
                <label class="cvi-modal__ack">
                    <input type="checkbox" id="cvi-drop-ack">
                    <?php esc_html_e('I understand this permanently deletes all imported crescent visibility data.', 'crescent-visibility'); ?>
                </label>
                <div class="cvi-modal__actions">
                    <button type="button" class="button" id="cvi-drop-cancel" data-cvi-close="1"><?php esc_html_e('Cancel', 'crescent-visibility'); ?></button>
                    <form method="post" style="display:inline; margin:0;">
                        <?php wp_nonce_field('crescent_drop_nonce'); ?>
                        <button type="submit" name="crescent_drop" id="cvi-drop-confirm" class="button button-primary cvi-danger-btn" disabled>
                            <?php esc_html_e('Yes, delete & recreate', 'crescent-visibility'); ?>
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <style>
            .cvi-danger-btn { color:#b32d2e !important; border-color:#b32d2e !important; }
            #cvi-drop-confirm.button-primary { background:#b32d2e; border-color:#8a1f1f; color:#fff !important; }
            #cvi-drop-confirm:disabled { opacity:.5; cursor:not-allowed; }
            .cvi-modal { position:fixed; inset:0; z-index:100000; display:flex; align-items:center; justify-content:center; }
            .cvi-modal[hidden] { display:none; }
            .cvi-modal__backdrop { position:absolute; inset:0; background:rgba(0,0,0,.55); }
            .cvi-modal__box { position:relative; background:#fff; border-radius:10px; max-width:460px; width:calc(100% - 40px);
                padding:22px 24px; box-shadow:0 20px 50px -12px rgba(0,0,0,.5); }
            .cvi-modal__title { margin:0 0 12px; font-size:18px; color:#b32d2e; }
            .cvi-modal__box code { font-size:12px; }
            .cvi-modal__ack { display:flex; gap:8px; align-items:flex-start; margin:14px 0 18px; font-weight:600; line-height:1.4; }
            .cvi-modal__ack input { margin-top:2px; }
            .cvi-modal__actions { display:flex; justify-content:flex-end; gap:10px; }
        </style>
        <script>
        (function () {
            var modal   = document.getElementById('cvi-drop-modal');
            var open    = document.getElementById('cvi-drop-open');
            var ack     = document.getElementById('cvi-drop-ack');
            var confirm = document.getElementById('cvi-drop-confirm');
            if (!modal || !open) { return; }
            function show() { modal.hidden = false; }
            function hide() { modal.hidden = true; ack.checked = false; confirm.disabled = true; }
            open.addEventListener('click', show);
            ack.addEventListener('change', function () { confirm.disabled = !ack.checked; });
            modal.querySelectorAll('[data-cvi-close]').forEach(function (el) { el.addEventListener('click', hide); });
            document.addEventListener('keydown', function (e) { if (e.key === 'Escape' && !modal.hidden) { hide(); } });
        })();
        </script>

        <hr>

        <h2><?php esc_html_e('Current Data Status', 'crescent-visibility'); ?></h2>
        <?php
        global $wpdb;
        $table = $wpdb->prefix . 'crescent_observations';
        $count = (int) $wpdb->get_var("SELECT COUNT(*) FROM $table");

        if ($count > 0) {
            echo '<p style="color: green;"><strong>' . esc_html__('✓ Data loaded:', 'crescent-visibility') . '</strong> '
                /* translators: %s: number of observation records */
                . esc_html(sprintf(_n('%s observation record in the database.', '%s observation records in the database.', $count, 'crescent-visibility'), number_format($count)))
                . '</p>';
        } else {
            echo '<p style="color: #b00;"><strong>' . esc_html__('No data imported yet.', 'crescent-visibility') . '</strong> '
                . esc_html__('Please upload a data file above.', 'crescent-visibility') . '</p>';
        }

        // Outcome of the most recent import attempt (persisted), visible on every load.
        $last = get_option('cvi_last_import');
        if (is_array($last)) {
            echo '<h3>' . esc_html__('Last Import Attempt', 'crescent-visibility') . '</h3>';
            echo '<table class="widefat striped" style="max-width:560px;"><tbody>';
            $row = function ($k, $v) { echo '<tr><td><strong>' . esc_html($k) . '</strong></td><td>' . esc_html($v) . '</td></tr>'; };
            /* translators for the diagnostic labels below are self-evident field names. */
            if (!empty($last['time']))          { $row(__('When', 'crescent-visibility'), $last['time']); }
            if (isset($last['file_size']))      { $row(__('Uploaded file size', 'crescent-visibility'), sprintf(__('%s bytes', 'crescent-visibility'), number_format((int) $last['file_size']))); }
            if (!empty($last['error']))         { $row(__('Result', 'crescent-visibility'), sprintf(__('FAILED — %s', 'crescent-visibility'), $last['error'])); }
            if (isset($last['found']))          { $row(__('Observations in file', 'crescent-visibility'), intval($last['found'])); }
            if (isset($last['imported']))       { $row(__('Stored this import', 'crescent-visibility'), intval($last['imported'])); }
            if (!empty($last['skipped']))       { $row(__('Skipped (missing city/new_moon)', 'crescent-visibility'), intval($last['skipped'])); }
            if (!empty($last['failed']))        { $row(__('DB errors', 'crescent-visibility'), intval($last['failed'])); }
            if (isset($last['stored_total']))   { $row(__('Total rows now in table', 'crescent-visibility'), intval($last['stored_total'])); }
            if (isset($last['id_column']))      { $row(__('id column type', 'crescent-visibility'), $last['id_column'] !== '' ? $last['id_column'] : __('(no AUTO_INCREMENT)', 'crescent-visibility')); }
            if (isset($last['indexes']))        { $row(__('Indexes', 'crescent-visibility'), $last['indexes']); }
            if (isset($last['distinct_pairs'])) { $row(__('Distinct city+date stored', 'crescent-visibility'), intval($last['distinct_pairs'])); }
            if (!empty($last['sample_rows']))   { $row(__('First stored rows', 'crescent-visibility'), $last['sample_rows']); }
            if (!empty($last['ddl_error']))     { $row(__('Table rebuild error', 'crescent-visibility'), $last['ddl_error']); }
            if (!empty($last['first_error']))   { $row(__('First DB error', 'crescent-visibility'), $last['first_error']); }
            if (!empty($last['first_skip']))    { $row(__('First skipped row', 'crescent-visibility'), $last['first_skip']); }
            echo '</tbody></table>';
        }
        ?>
    </div>
</div>
