<?php
if (!defined('ABSPATH')) exit;
?>
<div class="wrap">
    <h1>Crescent Visibility Data Management
        <span style="font-size:13px;color:#646970;font-weight:400;">(plugin v<?php echo esc_html(defined('CVI_VERSION') ? CVI_VERSION : '?'); ?>)</span>
    </h1>

    <div style="max-width: 800px;">
        <p><strong>This plugin does not contain any visibility data by default.</strong></p>
        
        <p>To use it, you must import a data file generated by the offline generator tool.</p>

        <h2>How to Use</h2>
        <ol>
            <li>Generate a <code>.json</code> data file with the project's generator. Years and cities are set there:<br>
                <code>go run generator/generate_visibility_data.go --start 2026 --end 2035 --cities jerusalem,dallas,melbourne --output ../data/visibility.json</code><br>
                <span style="color:#555;">The dropdown shows every city in the file (Jerusalem, Dallas and Melbourne are always included); the Year list shows every year in the file.</span>
            </li>
            <li>Upload that file below to import the data into your WordPress database.</li>
            <li>Use the shortcode on any page or post, for example:<br>
                <code>[crescent_visibility city="jerusalem" years="2026-2035"]</code>
            </li>
            <li><strong>New (recommended for most users):</strong> For the full interactive experience (like the web app "Visibility for My Location" tool):<br>
                <code>[crescent_visibility_interactive]</code> or <code>[crescent_visibility_point]</code><br>
                <span style="color:#555;">Optional attributes: <code>default_city="mecca"</code> and <code>theme="dark"</code> (matches the web app's zinc theme).</span>
            </li>
        </ol>

        <p><em>You can re-import updated data files at any time to refresh or extend the dataset (for example, adding 2029 data later).</em></p>

        <h3>Quick Verification After Install</h3>
        <ol>
            <li>Activate the plugin.</li>
            <li>Obtain a visibility JSON file (e.g. <code>visibility-2026-2035-real.json</code> from the generator) and upload it using the Import form below.</li>
            <li>Create a new page and add one of these shortcodes:
                <pre><code>[crescent_visibility_interactive]</code></pre>
                or the alias
                <pre><code>[crescent_visibility_point default_city="jerusalem" theme="dark"]</code></pre>
            </li>
            <li>Publish and view the page. You should see:
                <ul>
                    <li>City selector (defaults to Jerusalem + next new moon)</li>
                    <li>Working year and new moon dropdowns</li>
                    <li>Live-updating result cards when moving the sliders</li>
                    <li>A small context map</li>
                </ul>
            </li>
        </ol>
        <p>For the complete manual testing checklist (AJAX, dark theme, noscript fallback, etc.), see the <strong>Migration &amp; Testing Notes</strong> included with the plugin.</p>

        <div style="background:#fff3cd; border:1px solid #ffeaa7; padding:12px; border-radius:6px; margin:15px 0;">
            <strong>Important for the new interactive experience:</strong><br>
            The database is upgraded automatically when you update the plugin (the Age/Q columns are added if missing).
            However, those columns are only <em>populated</em> from your data file — so if you imported data before this
            update, please <strong>re-import your JSON file now</strong> so the rich result cards can display moon age and
            Q values (matching the web app).
        </div>

        <hr>

        <h2>Import Data</h2>
        <p>Upload a JSON file containing pre-computed visibility data.</p>

        <form method="post" enctype="multipart/form-data">
            <?php wp_nonce_field('crescent_import_nonce'); ?>
            <input type="file" name="import_file" accept=".json" required style="margin-bottom: 10px;">
            <br>
            <button type="submit" name="crescent_import" class="button button-primary">Import / Update Data</button>
        </form>

        <hr>

        <h2>Reset Database Tables</h2>
        <p>Permanently delete the plugin's tables (<code>observations</code> + <code>cities</code>) and recreate them empty.
           Use this if the data looks stuck or corrupted (e.g. only 1 row stored), then re-import. This does not affect any other plugin or content.</p>
        <?php
        global $wpdb;
        $cvi_drop_count = (int) $wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}crescent_observations");
        ?>
        <button type="button" class="button button-secondary cvi-danger-btn" id="cvi-drop-open">Drop &amp; Recreate Tables&hellip;</button>

        <!-- Confirmation modal -->
        <div id="cvi-drop-modal" class="cvi-modal" hidden>
            <div class="cvi-modal__backdrop" data-cvi-close="1"></div>
            <div class="cvi-modal__box" role="dialog" aria-modal="true" aria-labelledby="cvi-drop-title">
                <h2 id="cvi-drop-title" class="cvi-modal__title">⚠️ Delete all crescent visibility data?</h2>
                <p>This permanently deletes the <code><?php echo esc_html($wpdb->prefix); ?>crescent_observations</code> and
                   <code><?php echo esc_html($wpdb->prefix); ?>crescent_cities</code> tables and recreates them <strong>empty</strong>.
                   <strong>There is no undo.</strong> You will need to re-import your JSON afterward.</p>
                <p style="margin:10px 0;">Currently stored: <strong><?php echo number_format($cvi_drop_count); ?></strong> observation row<?php echo $cvi_drop_count === 1 ? '' : 's'; ?>.</p>
                <label class="cvi-modal__ack">
                    <input type="checkbox" id="cvi-drop-ack">
                    I understand this permanently deletes all imported crescent visibility data.
                </label>
                <div class="cvi-modal__actions">
                    <button type="button" class="button" id="cvi-drop-cancel" data-cvi-close="1">Cancel</button>
                    <form method="post" style="display:inline; margin:0;">
                        <?php wp_nonce_field('crescent_drop_nonce'); ?>
                        <button type="submit" name="crescent_drop" id="cvi-drop-confirm" class="button button-primary cvi-danger-btn" disabled>
                            Yes, delete &amp; recreate
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <style>
            .cvi-danger-btn { color:#b32d2e !important; border-color:#b32d2e !important; }
            #cvi-drop-confirm.button-primary { background:#b32d2e; border-color:#8a1f1f; color:#fff !important; }
            #cvi-drop-confirm:disabled { opacity:.5; cursor:not-allowed; }
            .cvi-modal { position:fixed; inset:0; z-index:100000; display:flex; align-items:center; justify-content:center; }
            .cvi-modal[hidden] { display:none; }
            .cvi-modal__backdrop { position:absolute; inset:0; background:rgba(0,0,0,.55); }
            .cvi-modal__box { position:relative; background:#fff; border-radius:10px; max-width:460px; width:calc(100% - 40px);
                padding:22px 24px; box-shadow:0 20px 50px -12px rgba(0,0,0,.5); }
            .cvi-modal__title { margin:0 0 12px; font-size:18px; color:#b32d2e; }
            .cvi-modal__box code { font-size:12px; }
            .cvi-modal__ack { display:flex; gap:8px; align-items:flex-start; margin:14px 0 18px; font-weight:600; line-height:1.4; }
            .cvi-modal__ack input { margin-top:2px; }
            .cvi-modal__actions { display:flex; justify-content:flex-end; gap:10px; }
        </style>
        <script>
        (function () {
            var modal   = document.getElementById('cvi-drop-modal');
            var open    = document.getElementById('cvi-drop-open');
            var ack     = document.getElementById('cvi-drop-ack');
            var confirm = document.getElementById('cvi-drop-confirm');
            if (!modal || !open) { return; }

            function show() { modal.hidden = false; }
            function hide() { modal.hidden = true; ack.checked = false; confirm.disabled = true; }

            open.addEventListener('click', show);
            ack.addEventListener('change', function () { confirm.disabled = !ack.checked; });
            modal.querySelectorAll('[data-cvi-close]').forEach(function (el) {
                el.addEventListener('click', hide);
            });
            document.addEventListener('keydown', function (e) {
                if (e.key === 'Escape' && !modal.hidden) { hide(); }
            });
        })();
        </script>

        <hr>

        <h2>Current Data Status</h2>
        <?php
        global $wpdb;
        $table = $wpdb->prefix . 'crescent_observations';
        $count = $wpdb->get_var("SELECT COUNT(*) FROM $table");

        if ($count > 0) {
            echo "<p style='color: green;'><strong>✓ Data loaded:</strong> " . intval($count) . " observation records in the database.</p>";
        } else {
            echo "<p style='color: #b00;'><strong>No data imported yet.</strong> Please upload a data file above.</p>";
        }

        // Show the outcome of the most recent import attempt (persisted), so it
        // is visible on every page load — not only right after submitting.
        $last = get_option('cvi_last_import');
        if (is_array($last)) {
            echo '<h3>Last Import Attempt</h3>';
            echo '<table class="widefat striped" style="max-width:560px;"><tbody>';
            $row = function ($k, $v) { echo '<tr><td><strong>' . esc_html($k) . '</strong></td><td>' . esc_html($v) . '</td></tr>'; };
            if (!empty($last['time']))                       { $row('When', $last['time']); }
            if (isset($last['file_size']))                   { $row('Uploaded file size', number_format((int) $last['file_size']) . ' bytes'); }
            if (!empty($last['error']))                      { $row('Result', 'FAILED — ' . $last['error']); }
            if (isset($last['found']))                       { $row('Observations in file', intval($last['found'])); }
            if (isset($last['imported']))                    { $row('Stored this import', intval($last['imported'])); }
            if (!empty($last['skipped']))                    { $row('Skipped (missing city/new_moon)', intval($last['skipped'])); }
            if (!empty($last['failed']))                     { $row('DB errors', intval($last['failed'])); }
            if (isset($last['stored_total']))                { $row('Total rows now in table', intval($last['stored_total'])); }
            if (isset($last['id_column']))                   { $row('id column type', $last['id_column'] !== '' ? $last['id_column'] : '(no AUTO_INCREMENT)'); }
            if (isset($last['indexes']))                     { $row('Indexes', $last['indexes']); }
            if (isset($last['distinct_pairs']))              { $row('Distinct city+date stored', intval($last['distinct_pairs'])); }
            if (!empty($last['sample_rows']))                { $row('First stored rows', $last['sample_rows']); }
            if (!empty($last['ddl_error']))                  { $row('Table rebuild error', $last['ddl_error']); }
            if (!empty($last['first_error']))                { $row('First DB error', $last['first_error']); }
            if (!empty($last['first_skip']))                 { $row('First skipped row', $last['first_skip']); }
            echo '</tbody></table>';
        }
        ?>
    </div>
</div>
